winxp
=====
Git-1.8.5.2-preview20131230.exe already installed
download and install python-3.4.0.msi

vezerlopult/rendszer/specialis/kornyezeti valtozok
  hunkis
    PATH ...;c:\python34;c:\python34\scripts

git bash
  $ python
  Python 3.4.0... (PATH change works)
  $ pip
  Usage:...
  $ vi .bashrc
  alias python3='c:\\Python34\\python.exe'
  alias pip-3.4='c:\\Python34\\Scripts\\pip.exe'
  
restart git bash
  $ python3
  Python 3.4.0... (PATH change works)

  $ pip-3.4 install django==1.6.1
  $ pip-3.4 install --upgrade selenium

================================================================================
1 - getting django set up using a functional test
================================================================================
create test

  $ cd "/d/documents and settings/hunkis/agco/dev/_misc/python/test_driven_dev_with_python"
  $ vi 01_01_functional_tests.py
  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
  from selenium import webdriver
  browser = webdriver.Chrome()
  browser.get('http://localhost:8000')
  assert 'Django' in browser.title
  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .

run it - fails

  $ python3 01_01_functional_tests.py
  ...
  ChromeDriver executable needs to be available in the path.
  Please download from http://chromedriver.storage.googleapis.com/index.html
  and read up at http://code.google.com/p/selenium/wiki/ChromeDriver

  download chromedriver_win32.zip from
    http://chromedriver.storage.googleapis.com/index.html?path=2.9/
  unzip and copy chromedriver.exe to c:\python34
    (not the proper place but is on PATH)

  $ python3 01_01_functional_tests.py
  ...opens chrome but
  ...assertion error

create project and start up django

  $ django-admin.py startproject superlists
  $ ls -R superlists
  (shell 1)$ cd superlists
  (shell 1)$ python3 manage.py runserver

run it again - succeeds
  
  (shell 2)$ cd "/d/documents and settings/hunkis/agco/dev/_misc/python/test_driven_dev_with_python/superlists"
{ (shell 2)$ mv ../01_01_functional_tests.py .   <=== !!! }
  (shell 2)$ python3 01_01_functional_tests.py
  ...lots of messages
  ...but no assertion error

commit changes to git

  (FROM NOW ON THE DEFAULT DIR IS /d/documents and settings/hunkis/agco/dev/_misc/python/test_driven_dev_with_python/superlists)
{ $ mv ../test_driven_dev_with_python.txt . }
{ $ mv test_driven_dev_with_python.txt test_driven_dev_with_python__superlists.txt }

  $ git init .
  $ git add .
  $ git status
  ...
  $ git rm -r --cached superlists/__pycache__
  $ echo "__pycache__" >>.gitignore
  $ echo "*.pyc" >>.gitignore
  $ git add .gitignore
  $ git status
  ...
  $ git commit
  ...opens vi
  ...into the first line insert
  first commit - first ft and basic django setup

================================================================================
2 - extending our functional test using the unittest module
================================================================================
